### ISSUE TITLE
RPC Server Bug

### ISSUE THREAD

**Issue by joesixpack** [segwit/atbcoin#1]
ATB does not respond to valid RPC commands sent to the wallet via bitcoinrpc.authproxy (Python).  The socket times out.  Server=1 is in the config file.  I do not have issues with any other wallet using identical RPC commands.

**Comment by vadimVoloshanov** [comment]
Hello! We tried to repeat your error, we used bitcoinrpc.authproxy (Python), but we didn`t get error or any problems.
We recommend you try reinstalling bitcoinrpc.authproxy. If this does not help you, then perhaps restarting the ATB core.
We really want to help you, but we need more information: logs, screenshots, under what circumstances you received this error.

**Comment by joesixpack** [comment]
This has been fixed in the latest release.
